---
output:
  word_document: default
  pdf_document: default
---

Dr. Ali Shilatifard                        03-06-2020
Editor, *Science Advances*

Dear Dr. Shilatifard,

Please find attached our manuscript titled “Marine species do not need visas: the transboundary nature of the world’s exploited marine species” submitted for publication in *Science Advances*. In this paper we highlight the large and under-recognized scale of transboundary fisheries and discuss associated challenges in achieving international fisheries management goals.

Last year *Nandini et al.[^1]* published a paper in Science demonstrating that marine fishes are connected globally by larvae. Here, we show that this connectivity importantly also extends to later life stages, as marine species movements span multiple Economic Exclusive Zones, with profound implications for the management of species of high importance for revenue generation and food security. We found that **67% of the world’s identified fished species are transboundary**. Our results further highlight that these species are responsible for **80% of global-EEZs catches and 78.5% of fisheries revenue over the last decade**. We also find that fisheries targeting transboundary species appear worse off than those mainly catching non-transboundary species. Our study has direct implications for the management of transboundary species, pointing to the urgent need for strengthened international cooperation in the management of these fisheries.


We recommend our paper to be handled by Deputy Editor Dr. Jeremy Jackson and Associate Editor Dr. Jennifer Jacquet and suggest the following reviewers: 

- Claire Armstrong, The Norwegian College of Fishery Science, Tromso, Norway claire.armstrong@uit.no  
- Gakushi Ishimura, Faculty of Agriculture Department of Food Production and Environmental Management, Iwate University, Morioka, Japan; gakugaku@iwate-u.ac.jp  
- Rebecca Selden, Wellesley College, Wellesley, MA, USA; bselden@wellesley.edu  
- Julia Xue, Shanghai Jiao Tong University; juliaxue@ouc.edu.cn  


This manuscript is not being considered for publication in any other journal. All data is available upon request and the code used to analyze the data can be found at https://github.com/jepa/FishForVisa. All contributing authors and institutions have been identified, and the authors have no competing financial interests. This manuscript has been reviewed and approved by all authors.

Thank you for your consideration of this submission.
Sincerely (on behalf of all authors),



Juliano Palacios Abrantes  
The Institute for Oceans and Fisheries  
The University of British Columbia

[^1]: 1.	N. Ramesh, J. A. Rising, K. L. Oremus, The small world of global marine fisheries: The cross-boundary consequences of larval dispersal. Science. 364, 1192–1196 (2019).